### ISSUE TITLE
amountOutMin is not correct.

### ISSUE THREAD

**Issue by alphadev102** [thorswap/cross-chain-api-examples#2]
I tried to exchange 3.45327 avax USDC.e to ETH.
https://api.thorswap.net/aggregator/tokens/quote?sellAsset=AVAX.USDC.e-0xA7D7079b0FEaD91F3e65f86E8915Cb59c1a4C664&buyAsset=ETH.ETH&sellAmount=3.45327&senderAddress=sender&recipientAddress=recipient&providers=TRADERJOE&providers=THORCHAIN

```
      "calldata": {
        "tcRouter": "0x8F66c4AE756BEbC49Ec8B81966DD8bba9f127549",
        "tcVault": "0xc85656ab89531f8a6f309fe90705d7414d18330a",
        "tcMemo": "=:ETH.ETH:recipient:0:t:0",
        "token": "0xa7d7079b0fead91f3e65f86e8915cb59c1a4c664",
        "amount": "3453270",
        "amountOutMin": "192411650485436893",
        "deadline": "1674676839"
      }
```

here amountOutMin is 0.1924.. ETH. Is it possible?
It's not correct.

**Comment by ochhii1337** [comment]
Yes it looks like the decimals are off on this example. I will look and resolve. Thank you for raising this.

**Comment by ochhii1337** [comment]
Hi @alphadev102 the `amountOutMin` value here is in reference to the amount of AVAX that our aggregator contract will guarantee. This is required to protect users from mev.

The amount of ETH you will receive from the trade can be found in the `expectedOutput` prop.
